### PR TITLE
Release

### PR DESCRIPTION
**Pull request by ThibaultLSDC**

### CODE REVIEW

**Review by recursix — DISMISSED** [review]

**Comment by recursix** [comment]
@xhluca , yes we'll be working on dev and pushing to main a bit less frequently. We want to make more tests before pushing to minimize disruptions

**Comment by xhluca** [comment]
Thank you makes sense

**Review by recursix — DISMISSED** [review]

**Comment by ThibaultLSDC** [comment]
Tests pass

**Review by gasse — APPROVED** [review]
Let's merge!

**Pull request merged**
